FROM debian:10.9 as build

RUN apt-get update

RUN apt-get install -y \
  libssl-dev \
  libboost-dev \
  libboost-thread-dev \
  libboost-iostreams-dev \
  libboost-system-dev \
  libboost-program-options-dev \
  libpcre3-dev \
  libicu-dev \
  zlib1g-dev \
  libevent-dev \
  libhiredis-dev \
  build-essential \
  manpages-dev \
  automake \
  autoconf \
  libstdc++6 \
  libgcrypt-dev \
  libgflags-dev \
  libssl1.1 \
  libboost-filesystem1.67.0 \
  gcc \
  g++ \
  cmake

RUN rm -rf /var/lib/apt/lists/*

RUN apt-get update

SHELL ["/bin/bash", "-c"]

#ADD ./ /app/

WORKDIR /app/

CMD ["./run.sh"]